### ISSUE TITLE
php 7.4 on macos

### ISSUE THREAD

**Issue by if4lcon** [phpbrew/phpbrew#1040]
Alternatively, you may set the environment variables OPENSSL_CFLAGS

and OPENSSL_LIBS to avoid the need to call pkg-config.

See the pkg-config man page for more details.

no matter what command I changed I even copied php 7.3 configure parameters from homebrew

**Comment by bskiefer** [comment]
Not sure if this helps in your case, but my fix was to add the following to my `.bashrc`/`.zshrc` file.

```
CPPFLAGS=-I/usr/local/opt/openssl/include:"${CPPFLAGS}"  
LD_LIBRARY_PATH=/usr/local/Cellar/openssl/1.0.2s/lib:"${LD_LIBRARY_PATH}"
CPATH=/usr/local/opt/openssl/include:"${CPATH}"  
PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2s/lib/pkgconfig:"${PKG_CONFIG_PATH}"          
export LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH CPPFLAGS
```

May have to adjust as necessary, but as you can tell I'm using brew's openssl for pkg config & LD.

**Comment by if4lcon** [comment]
thank you ... unfortunately didn't compile

```
Alternatively, you may set the environment variables SASL_CFLAGS

and SASL_LIBS to avoid the need to call pkg-config.

See the pkg-config man page for more details.```

**Comment by ramsey** [comment]
I'm having the same problem. It looks like phpbrew can no longer find the Homebrew libraries.

**Comment by bskiefer** [comment]
@ramsey What error are you getting? It's sometimes useful to run `brew link {{package}} --force`, or reinstalling the dependency. However I had to liter my .zshrc with exports to get everything to work correctly.

I'll just include a few that solved my issues

```

export CPPFLAGS=-I/usr/local/opt/openssl/include:"${CPPFLAGS}"  
export CPPFLAGS=-I/usr/local/opt/libedit/include:"${CPPFLAGS}"  
export CPPFLAGS=-I/usr/local/Cellar/readline/8.0.1/include:"${CPPFLAGS}"  

export LD_LIBRARY_PATH=/usr/local/Cellar/openssl/1.0.2s/lib:"${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH=/usr/local/opt/libedit/lib:"${LD_LIBRARY_PATH}"  
export LD_LIBRARY_PATH=/usr/local/Cellar/readline/8.0.1/lib:"${LD_LIBRARY_PATH}" 

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libedit/lib/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/Cellar/readline/8.0.1/lib/pkgconfig

export EXTRA_LIBS="/usr/local/Cellar/readline/8.0.1/lib/libhistory.dylib 
/usr/local/Cellar/readline/8.0.1/lib/libreadline.dylib"

```

Which now works with the following config.yaml

```
variants:
    dev:
        bcmath:
        calendar:
        cli:
        ctype:
        dom:
        fileinfo:
        filter:
        ipc:
        iconv:
        json:
        mbregex:
        mbstring:
        mhash:
        mcrypt:
        pcntl:
        pcre:
        pdo:
        phar:
        posix:
        sockets:
        tokenizer:
        xml:
        curl:
        openssl:
        zip:
        gd:
          - --with-gmp=/usr/local/opt
          - --with-openssl
          - --enable-gd
          - --with-zlib-dir=/usr/local/opt/zlib
          - --enable-xml
          - --enable-libxml
          - --with-gd
          - --with-readline=/opt/local
          - --with-iconv=/opt/local
extensions:
    dev:
        xdebug: stable
        redis: stable
```
