### ISSUE TITLE
is there a way to specify extra parameters for extension presents?

### ISSUE THREAD

**Issue by Gamesh** [phpbrew/phpbrew#821]
I could not find in wiki how to specify for extension presents additional parameters.
```yml
extensions:
  mypresent:
    opcache: stable
    xdebug: stable
    # required for cli colors
    posix: stable
    # need to install manually: phpbrew ext install ldap stable -- --with-libdir=lib64
    ldap: stable
````

is there a way i can specify to install stable version of ldap with --with-libdir=lib64 in yml format ?

the equivalent of:
`phpbrew ext install ldap -- --with-libdir=lib64`
