### ISSUE TITLE
phpbrew ext install +foo ignores the hard-coded version number in the config.yaml

### ISSUE THREAD

**Issue by Sweetchuck** [phpbrew/phpbrew#869]
The PECL downloader uses the latest _stable_ release even if the desired version number is specified in the `config.yaml`.

content of the `~/.phpbrew/config.yaml`
```yaml
variants: []
extensions:
  my_pack_01:
    yaml: '2.0.0'
```
`phpbrew switch 7.1.4`
`phpbrew ext install +my_pack_01`

downloads the `1.3.0` version
```
Downloading https://pecl.php.net/rest/r/yaml/1.3.0.xml via curl extension
```
