### ISSUE TITLE
Add full example of `phpbrew.yml`

### ISSUE THREAD

**Issue by aeimer** [phpbrew/phpbrew#977]
I'd love to have a full example of the `phpbrew.yml`. For the [wikipage](https://github.com/phpbrew/phpbrew/wiki/Setting-up-Configuration#the-yaml-configuration-file) I'd suggest something like:

```
variants:
  custom:
    default:
    mysql: latest
    pdo: 1.2.3
    curl: latest -- --example-arg
    imap:
        - --with-kerberos
        - --with-imap-ssl
    sqlite:
      - 1.2.3
      - --
      - --exmaple-arg
    xml:
    iconv:

extensions:
  set1:
    apcu: 4.0.11
    ldap:
      - latest
      - --
      - --with-libdir=lib/x86_64-linux-gnu
    memcached: 2.2.0 -- --disable-memcached-sasl
    soap: latest
    xdebug: 2.5.5
    gd: latest -- --enable-gd-native-ttf --with-gd=shared --with-freetype-dir=/usr/include/freetype2/freetype --with-jpeg-dir=/usr --with-libdir=lib/x86_64-linux-gnu --with-png-dir=/usr --with-vpx-dir=/usr --with-xpm-dir=/usr
```
